#!/usr/bin/env python3
"""
Create Wannier90 .win Template File

This creates a properly configured .win file for Bismuth with SOC,
ready for wannier90.x -pp preprocessing.

Usage:
    python3 create_win_template.py --input tests/Bismuth_basis_40.out --seedname bismuth_improved
"""

import argparse
import sys
import numpy as np
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from lcao_wannier import (
    parse_calculation_parameters,
    parse_overlap_and_fock_matrices,
    parse_atoms_from_crystal_output,
)


def create_win_template(input_file, seedname, num_wann=12, num_bands=20):
    """
    Create a .win template file with proper SOC settings.
    """
    print(f"Creating Wannier90 template for: {seedname}")
    print(f"Input: {input_file}")
    print()

    # Parse CRYSTAL output
    with open(input_file, 'r') as f:
        lines = f.readlines()

    params = parse_calculation_parameters(lines)
    raw_matrices, lattice_vectors_list = parse_overlap_and_fock_matrices(lines)
    atoms, _ = parse_atoms_from_crystal_output(lines)

    lattice_vectors = np.array(lattice_vectors_list)

    print(f"✓ Fermi energy: {params.fermi_energy:.6f} eV")
    print(f"✓ K-grid: {params.k_grid}")
    print(f"✓ Atoms: {len(atoms)}")
    print()

    # Atoms are already in fractional coordinates from parse_atoms_from_crystal_output
    atoms_frac = atoms

    # Create .win file content
    win_content = f"""! Generated by LCAO-to-Wannier90 package
! Wannier90 input file for seedname: {seedname}
!

!====================
! SYSTEM PARAMETERS
!====================
num_wann = {num_wann}
num_bands = {num_bands}

! Fermi energy (for relative energy windows)
fermi_energy = {params.fermi_energy:.6f}

! Spin-orbit coupling included
spinors = .true.

!====================
! WANNIERIZATION
!====================
num_iter = 5000
conv_tol = 1.00e-10
conv_window = 5
num_print_cycles = 10

! Disentanglement windows (eV, relative to Fermi energy)
! Outer window: wide enough to capture 16-20 bands for disentanglement
dis_win_min = -25.0
dis_win_max = 10.0
! Frozen window: bands near Fermi level (-4.25 to 1.51 eV range)
dis_froz_min = -4.5
dis_froz_max = 2.0
dis_num_iter = 1000
dis_mix_ratio = 0.5

!====================
! OUTPUT OPTIONS
!====================
write_hr = T
write_xyz = T
write_r2mn = F

!====================
! UNIT CELL
!====================
begin unit_cell_cart
Ang
"""

    # Add lattice vectors
    for i in range(3):
        win_content += f"     {lattice_vectors[i,0]:18.12f} {lattice_vectors[i,1]:18.12f} {lattice_vectors[i,2]:18.12f}\n"

    win_content += "end unit_cell_cart\n\n"

    # Add atoms
    if atoms_frac:
        win_content += "!====================\n"
        win_content += "! ATOMS\n"
        win_content += "!====================\n"
        win_content += "begin atoms_frac\n"
        for symbol, pos in atoms_frac:
            win_content += f"{symbol:2s} {pos[0]:12.6f} {pos[1]:12.6f} {pos[2]:12.6f}\n"
        win_content += "end atoms_frac\n\n"

    # Add projections
    win_content += """!====================
! PROJECTIONS
!====================
! Option 1: Automatic (6 orbitals × 2 spinor = 12 WFs)
begin projections
Bi:p
end projections

! Option 2: Manual (5 orbitals × 2 spinor = 10 WFs)
! Uncomment below and comment out Option 1 if you want 10 WFs
!begin projections
"""
    if atoms_frac:
        win_content += f"!f={atoms_frac[0][1][0]:.6f},{atoms_frac[0][1][1]:.6f},{atoms_frac[0][1][2]:.6f}:px\n"
        win_content += f"!f={atoms_frac[0][1][0]:.6f},{atoms_frac[0][1][1]:.6f},{atoms_frac[0][1][2]:.6f}:py\n"
        win_content += f"!f={atoms_frac[0][1][0]:.6f},{atoms_frac[0][1][1]:.6f},{atoms_frac[0][1][2]:.6f}:pz\n"
        if len(atoms_frac) > 1:
            win_content += f"!f={atoms_frac[1][1][0]:.6f},{atoms_frac[1][1][1]:.6f},{atoms_frac[1][1][2]:.6f}:px\n"
            win_content += f"!f={atoms_frac[1][1][0]:.6f},{atoms_frac[1][1][1]:.6f},{atoms_frac[1][1][2]:.6f}:py\n"
    win_content += "!end projections\n\n"

    # Add k-points
    win_content += "!====================\n"
    win_content += "! K-POINT MESH\n"
    win_content += "!====================\n"
    win_content += f"mp_grid = {params.k_grid[0]} {params.k_grid[1]} {params.k_grid[2]}\n\n"

    # Generate k-point list
    win_content += "begin kpoints\n"
    nk1, nk2, nk3 = params.k_grid
    for ik3 in range(nk3):
        for ik2 in range(nk2):
            for ik1 in range(nk1):
                k1 = ik1 / nk1 if nk1 > 1 else 0.0
                k2 = ik2 / nk2 if nk2 > 1 else 0.0
                k3 = ik3 / nk3 if nk3 > 1 else 0.0
                win_content += f"     {k1:18.12f} {k2:18.12f} {k3:18.12f}\n"
    win_content += "end kpoints\n"

    # Write file
    win_filename = f"{seedname}.win"
    with open(win_filename, 'w') as f:
        f.write(win_content)

    print(f"✓ Created: {win_filename}")
    print()
    print("Configuration:")
    print(f"  num_wann = {num_wann}")
    print(f"  num_bands = {num_bands}")
    print(f"  spinors = .true.")
    print(f"  projections = Bi:p")
    print(f"  disentanglement = ENABLED")
    print()
    print("Next steps:")
    print(f"  1. Review {win_filename}")
    print(f"  2. Run: wannier90.x -pp {seedname}")
    print(f"  3. Then run Stage 2 with the .nnkp file")
    print()

    return win_filename


def main():
    parser = argparse.ArgumentParser(
        description='Create Wannier90 .win template file'
    )
    parser.add_argument('--input', required=True, help='CRYSTAL output file')
    parser.add_argument('--seedname', required=True, help='Wannier90 seedname')
    parser.add_argument('--num-wann', type=int, default=12, help='Number of Wannier functions (default: 12)')
    parser.add_argument('--num-bands', type=int, default=16, help='Number of bands (default: 16)')

    args = parser.parse_args()

    if not Path(args.input).exists():
        print(f"Error: Input file not found: {args.input}")
        sys.exit(1)

    create_win_template(args.input, args.seedname, args.num_wann, args.num_bands)


if __name__ == '__main__':
    main()
