"""
K-Point Grid Module

This module contains functions for generating k-point grids and neighbor lists
with periodic boundary conditions.
"""

import numpy as np
from typing import Tuple, Dict, List, Optional, Any


def generate_kpoint_grid(k_grid: Tuple[int, int, int]) -> np.ndarray:
    """
    Generate a Monkhorst-Pack k-point grid in fractional coordinates.
    
    The k-points are uniformly distributed in the first Brillouin zone
    using fractional coordinates: k = (i/nk1, j/nk2, k/nk3).
    
    Parameters
    ----------
    k_grid : tuple of 3 ints
        Dimensions of the k-point grid (nk1, nk2, nk3)
    
    Returns
    -------
    kpoints : ndarray of shape (num_kpoints, 3)
        Array of k-points in fractional coordinates
    
    Examples
    --------
    >>> k_grid = (2, 2, 2)
    >>> kpoints = generate_kpoint_grid(k_grid)
    >>> print(kpoints.shape)
    (8, 3)
    >>> print(kpoints[0])
    [0. 0. 0.]
    """
    nk1, nk2, nk3 = k_grid
    kpoints = []

    # Loop order matches Wannier90: k3 varies fastest, then k2, then k1
    # For 2D systems (nk3=1), this means k1 varies fastest
    # This matches the ordering in the .nnkp file
    for k in range(nk3):
        for j in range(nk2):
            for i in range(nk1):
                kx = i / nk1
                ky = j / nk2
                kz = k / nk3
                kpoints.append([kx, ky, kz])

    return np.array(kpoints)


def read_nnkp_neighbors(
    nnkp_file: str,
    recip_lattice: Optional[np.ndarray] = None,
    kpoints: Optional[np.ndarray] = None,
) -> Dict[int, List[Dict[str, Any]]]:
    """
    Read neighbor list from Wannier90 .nnkp file with Cartesian b-vectors.

    The .nnkp file is generated by 'wannier90.x -pp' and contains the exact
    neighbor structure that Wannier90 expects for the .mmn file.

    Parameters
    ----------
    nnkp_file : str
        Path to the .nnkp file
    recip_lattice : ndarray, optional
        Reciprocal lattice vectors in Cartesian coords (3x3 matrix, columns are vectors).
        If None, will be read from the .nnkp file. Used to compute Cartesian b-vectors.
    kpoints : ndarray of shape (num_kpoints, 3), optional
        K-points in fractional coordinates. If provided, b_vec_cart is computed
        correctly as recip_lattice @ (kpoints[k_next] + G_shift - kpoints[k]).
        If not provided, will be read from the .nnkp file.

    Returns
    -------
    neighbor_list : dict
        Maps k_idx (0-based) -> list of neighbor info dicts
        Each dict contains:
            'id': neighbor k-point index (0-based)
            'G_shift': lattice vector (n1, n2, n3) as integers
            'b_vec_cart': Cartesian b-vector (if recip_lattice available)

    Notes
    -----
    The .nnkp file uses 1-based indexing, which is converted to 0-based.
    The Cartesian b-vector is: b_cart = recip_lattice @ (k_next + G - k_curr)
    where k_next, k_curr are in fractional coordinates and G is the integer
    BZ folding vector.
    """
    neighbor_list = {}

    with open(nnkp_file, 'r') as f:
        file_lines = f.readlines()

    # Find the reciprocal lattice block if not provided
    if recip_lattice is None:
        for i, line in enumerate(file_lines):
            if 'begin recip_lattice' in line:
                recip_lines = []
                for j in range(1, 4):
                    recip_lines.append([float(x) for x in file_lines[i+j].split()])
                recip_lattice = np.array(recip_lines).T  # columns are vectors
                break

    # Read k-points from .nnkp if not provided
    if kpoints is None:
        for i, line in enumerate(file_lines):
            if 'begin kpoints' in line:
                num_kpts = int(file_lines[i+1].strip())
                kpoints = np.zeros((num_kpts, 3))
                for j in range(num_kpts):
                    kpoints[j] = [float(x) for x in file_lines[i+2+j].split()]
                break

    # Find the nnkpts block
    start_idx = None
    for i, line in enumerate(file_lines):
        if 'begin nnkpts' in line:
            start_idx = i
            break

    if start_idx is None:
        raise ValueError(f"Could not find 'begin nnkpts' block in {nnkp_file}")

    # Read number of neighbors per k-point
    num_neighbors = int(file_lines[start_idx + 1].strip())

    # Read neighbor data
    current_line = start_idx + 2
    while current_line < len(file_lines) and 'end nnkpts' not in file_lines[current_line]:
        parts = file_lines[current_line].split()
        if len(parts) == 5:
            k_idx_1based = int(parts[0])
            neighbor_idx_1based = int(parts[1])
            G_shift = np.array([int(parts[2]), int(parts[3]), int(parts[4])], dtype=int)

            # Convert to 0-based indexing
            k_idx = k_idx_1based - 1
            neighbor_idx = neighbor_idx_1based - 1

            if k_idx not in neighbor_list:
                neighbor_list[k_idx] = []

            # Create neighbor info dict
            neighbor_info = {
                'id': neighbor_idx,
                'G_shift': G_shift
            }

            # Compute CORRECT Cartesian b-vector:
            # b_frac = kpoints[neighbor] + G_shift - kpoints[k]
            # b_cart = recip_lattice @ b_frac
            if recip_lattice is not None and kpoints is not None:
                b_frac = kpoints[neighbor_idx] + G_shift - kpoints[k_idx]
                b_vec_cart = recip_lattice @ b_frac
                neighbor_info['b_vec_cart'] = b_vec_cart
            elif recip_lattice is not None:
                # Fallback: only G-shift contribution (less accurate)
                b_vec_cart = recip_lattice @ G_shift
                neighbor_info['b_vec_cart'] = b_vec_cart

            neighbor_list[k_idx].append(neighbor_info)

        current_line += 1

    return neighbor_list


def convert_neighbor_list_to_dict_format(
    neighbor_list_old: Dict[int, List[Tuple[int, np.ndarray]]],
    recip_lattice: np.ndarray,
    kpoints: Optional[np.ndarray] = None,
) -> Dict[int, List[Dict[str, Any]]]:
    """
    Convert old neighbor list format to new dict format.

    Old format: {k_idx: [(k_next_idx, G_shift), ...]}
    New format: {k_idx: [{'id': k_next_idx, 'G_shift': G, 'b_vec_cart': b}, ...]}

    Parameters
    ----------
    neighbor_list_old : dict
        Old format neighbor list where G_shift uses Wannier90 convention:
        (0,0,0) for interior neighbors, ±1 only at BZ boundary wrapping.
    recip_lattice : ndarray of shape (3, 3)
        Reciprocal lattice matrix with rows as reciprocal vectors
        (convention: a_i · b_j = 2π δ_ij).
    kpoints : ndarray of shape (num_kpoints, 3), optional
        K-points in fractional coordinates. If provided, b_vec_cart is
        computed correctly from k-point positions. If not provided,
        only the G_shift contribution is used (less accurate for
        interior neighbors where G_shift=0).

    Returns
    -------
    neighbor_list_new : dict
        New format with Cartesian b-vectors
    """
    neighbor_list_new = {}

    for k_idx, neighbors in neighbor_list_old.items():
        neighbor_list_new[k_idx] = []

        for k_next_idx, G_shift in neighbors:
            G_shift = np.asarray(G_shift, dtype=float)

            # Compute Cartesian b-vector from fractional coordinates
            if kpoints is not None:
                b_frac = kpoints[k_next_idx] + G_shift - kpoints[k_idx]
            else:
                b_frac = G_shift
            # recip_lattice has rows as vectors → transpose for conversion
            b_vec_cart = recip_lattice.T @ b_frac

            neighbor_dict = {
                'id': k_next_idx,
                'G_shift': np.asarray(G_shift, dtype=int),
                'b_vec_cart': b_vec_cart
            }
            neighbor_list_new[k_idx].append(neighbor_dict)

    return neighbor_list_new


def generate_neighbor_list(
    k_grid: Tuple[int, int, int]
) -> Dict[int, List[Tuple[int, np.ndarray]]]:
    """
    Generate a neighbor list for all k-points in the grid.

    Generates neighbors in ±x, ±y, ±z directions with periodic boundary conditions.
    For 2D systems (e.g., nk3=1), only generates neighbors in directions where
    the grid has more than 1 point, matching Wannier90's expectations.

    Parameters
    ----------
    k_grid : tuple of 3 ints
        Dimensions of the k-point grid (nk1, nk2, nk3)

    Returns
    -------
    neighbor_list : dict
        Maps k_idx -> list of (neighbor_idx, lattice_vector_b) tuples
        where lattice_vector_b is the connecting vector in k-space

    Notes
    -----
    - For 3D systems (nk1,nk2,nk3 > 1): 6 neighbors per k-point
    - For 2D systems (e.g., nk3=1): 4 neighbors per k-point (no ±z)
    - For 1D systems (e.g., nk2=nk3=1): 2 neighbors per k-point (only ±x)

    Examples
    --------
    >>> k_grid = (3, 3, 3)
    >>> neighbor_list = generate_neighbor_list(k_grid)
    >>> len(neighbor_list[0])  # 3D: 6 neighbors
    6

    >>> k_grid = (8, 8, 1)
    >>> neighbor_list = generate_neighbor_list(k_grid)
    >>> len(neighbor_list[0])  # 2D: 4 neighbors
    4
    """
    nk1, nk2, nk3 = k_grid
    neighbor_list = {}

    # Build direction list based on grid dimensions
    # Only include directions where the grid has more than 1 point
    directions = []

    # ±x direction (only if nk1 > 1)
    if nk1 > 1:
        directions.extend([(1, 0, 0), (-1, 0, 0)])

    # ±y direction (only if nk2 > 1)
    if nk2 > 1:
        directions.extend([(0, 1, 0), (0, -1, 0)])

    # ±z direction (only if nk3 > 1)
    if nk3 > 1:
        directions.extend([(0, 0, 1), (0, 0, -1)])

    for i in range(nk1):
        for j in range(nk2):
            for k in range(nk3):
                k_idx = i * nk2 * nk3 + j * nk3 + k
                neighbors = []

                for di, dj, dk in directions:
                    # Apply periodic boundary conditions
                    ni = (i + di) % nk1
                    nj = (j + dj) % nk2
                    nk = (k + dk) % nk3

                    neighbor_idx = ni * nk2 * nk3 + nj * nk3 + nk

                    # Wannier90-convention G_shift:
                    # G is (0,0,0) for interior neighbors.
                    # G is ±1 only when BZ boundary wrapping occurs,
                    # such that kpoints[neighbor] + G = kpoints[k] + delta_k.
                    G = np.zeros(3, dtype=int)
                    if i + di < 0:
                        G[0] = -1
                    elif i + di >= nk1:
                        G[0] = 1
                    if j + dj < 0:
                        G[1] = -1
                    elif j + dj >= nk2:
                        G[1] = 1
                    if k + dk < 0:
                        G[2] = -1
                    elif k + dk >= nk3:
                        G[2] = 1

                    neighbors.append((neighbor_idx, G))

                neighbor_list[k_idx] = neighbors

    return neighbor_list


def kpoint_index_to_grid(k_idx: int, k_grid: Tuple[int, int, int]) -> Tuple[int, int, int]:
    """
    Convert linear k-point index to grid indices.
    
    Parameters
    ----------
    k_idx : int
        Linear k-point index
    k_grid : tuple of 3 ints
        Dimensions of the k-point grid
    
    Returns
    -------
    tuple of 3 ints
        Grid indices (i, j, k)
    """
    nk1, nk2, nk3 = k_grid
    i = k_idx // (nk2 * nk3)
    remainder = k_idx % (nk2 * nk3)
    j = remainder // nk3
    k = remainder % nk3
    return i, j, k


def grid_to_kpoint_index(i: int, j: int, k: int, k_grid: Tuple[int, int, int]) -> int:
    """
    Convert grid indices to linear k-point index.
    
    Parameters
    ----------
    i, j, k : int
        Grid indices
    k_grid : tuple of 3 ints
        Dimensions of the k-point grid
    
    Returns
    -------
    int
        Linear k-point index
    """
    nk1, nk2, nk3 = k_grid
    return i * nk2 * nk3 + j * nk3 + k